-- Cleanup script for test data generated by scripts/test_all.sh and scripts/test_edge_cases.sh
-- Uses TEST_PREFIX (default: [TEST] ).

begin;

-- Set prefix (edit if needed)
-- Example: set prefix to '[TEST] '

-- Cleanup checklists
-- replace '[TEST] ' if you changed TEST_PREFIX

delete from checklists
where title ilike '[TEST] %';

delete from tasks
where title ilike '[TEST] %';

delete from projects
where name ilike '[TEST] %';

delete from areas
where name ilike '[TEST] %';

commit;
